### ISSUE TITLE
Add a README.MD file

### ISSUE THREAD

**Issue by StrangeOne101** [StrangeOne101/Paralyze#1]
# Overview
Just a simple request to add a readme to this repo. All information about it can be found at https://projectkorra.com/forum/resources/realistic-paralyze.236/

# Requirements
Nothing complicated. Just a readme in the same format as this one: https://github.com/StrangeOne101/JackOSplosion/blob/master/README.md

However the graphic shown on the overview page would be a nice touch, too

**Comment by bamsarts** [comment]
i am in

**Comment by StrangeOne101** [comment]
Closed, implemented in #3
